// Dados Reais de Escalada — Algodão de Jandaíra (PB) & Falésias Brasileiras
import { Sector, ClimbingDestination } from '../types/climbing';

export const MOCK_SECTORS: Sector[] = [
  // SETOR 1: ALGODÃO DE JANDAÍRA - PARAÍBA (XII EENe 2013)
  {
    id: 'sector-algodao-jandaira',
    name: 'Algodão de Jandaíra',
    cragName: 'Polo de Escalada da Paraíba',
    region: 'Curimataú Ocidental',
    city: 'Algodão de Jandaíra',
    state: 'PB',
    coordinates: {
      latitude: -6.8647,
      longitude: -35.9861,
    },
    elevationMeters: 540,
    approachTimeMinutes: 12,
    approachTrailDescription: 'A partir de Remígio pela BR-104 (14 km). Em Algodão de Jandaíra, seguir pelas estradas de terra até os estacionamentos das casas locais (Seu Toinho e Seu Antônio). Trilhas bem demarcadas com totens de pedra até a base dos inselbergues.',
    accessStatus: 'aberto',
    accessNotes: 'Propriedade particular e área de preservação do semiárido. Sempre feche as porteiras, não deixe lixo e respeite os moradores locais (Seu Antônio e Seu Toinho).',
    history: 'Sede do memorável XII Encontro de Escaladores do Nordeste (EENe 2013). Desbravado com muito suor pela comunidade de escaladores da Paraíba, Rio Grande do Norte e Ceará. Famoso pelo granito claro de altíssima aderência, com generosas agarras (pinças, regletes, abaulados e agarrões), fendas perfeitas para móvel e vias esportivas de extrema qualidade.',
    rules: [
      'Proibido fazer fogueiras — o semiárido e a caatinga são altamente vulneráveis ao fogo',
      'Não deixe lixo — traga de volta todas as embalagens',
      'Respeite as pinturas rupestres locais na Pedra Furada',
      'Não altere o padrão de proteção das vias nem cave agarras artificiais',
      'Desça preferencialmente pela trilha de caminhada ou rapel em paradas duplas com backup de prussik',
    ],
    walls: [
      // PAREDE 1: PEDRA FURADA (Com Modelo 3D & Croqui 2D do teto da gruta)
      {
        id: 'wall-pedra-furada',
        sectorId: 'sector-algodao-jandaira',
        name: 'Pedra Furada (Face Leste)',
        orientation: 'L',
        sunShadeNotes: 'Sol pela manhã até o meio-dia. Sombra fresca e abrigo do vento durante toda a tarde.',
        sunExposure: {
          morning: 'sol',
          afternoon: 'sombra',
        },
        heightMeters: 25,
        rockType: 'granito',
        approachNotes: 'Caminhada plana de 12 minutos a partir do estacionamento da estrada sentido Pedra Furada.',
        history: 'A face mais icônica de Algodão de Jandaíra, marcada por uma enorme cavidade/gruta de teto negativo no terço superior. Conquistada entre 2008 e 2013 por lendas da escalada como Cauí Vieira, Wolgrand Falcão, Stenio Torres, Fabricio Leite e Ítalo Costa.',
        fallbackPhotoUrl: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1200&q=80',
        photos: [
          {
            id: 'photo-pf-1',
            url: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1200&q=80',
            caption: 'Face Leste da Pedra Furada com o grande teto da caverna',
            isMain: true,
          }
        ],
        // NÍVEL 1: MODELO 3D REAL DA PEDRA FURADA
        model3D: {
          id: 'model-pedra-furada-3d',
          wallId: 'wall-pedra-furada',
          isProceduralMesh: true,
          dimensionsMeters: {
            width: 32,
            height: 25,
            depth: 8,
          },
          cameraPresets: {
            initialPosition: [0, 8, 28],
            target: [0, 10, 0],
            minDistance: 8,
            maxDistance: 45,
          },
          meshPolyCount: 52000,
          photogrammetrySource: {
            photoCount: 310,
            resolution: '4K PBR',
            dateCaptured: '2024-07-20',
          }
        },
        // NÍVEL 2: CROQUI 2D VETORIAL DA PEDRA FURADA
        activeTopo2D: {
          id: 'topo-pedra-furada-2d',
          wallId: 'wall-pedra-furada',
          imageUrl: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1200&q=80',
          width: 1200,
          height: 800,
          aspectRatio: 1.5,
          photographer: 'Guia XII EENe 2013',
        },
        routes: [
          {
            id: 'route-pf-01',
            wallId: 'wall-pedra-furada',
            orderIndex: 1,
            name: '905 Irajá x Bonsucesso',
            grade: { brazilian: 'IV', french: '4c', yds: '5.6', danger: 'E1' },
            heightMeters: 10,
            pitchesCount: 1,
            boltsCount: 3,
            protectionType: 'movel',
            rackRequired: 'Peças pequenas de móvel para fendas horizontais',
            anchorType: 'dupla_com_anel',
            style: 'tradicional',
            firstAscent: { climbers: ['Ítalo Costa', 'Dalton Chiarelli'], year: 2008 },
            description: 'Via curta e vertical protegida em móvel, peças pequenas em fendas e buracos horizontais. Rapel compartilhado em parada dupla.',
            geometry3D: {
              routeId: 'route-pf-01',
              color: '#10B981',
              tubeRadius: 0.05,
              startPoint3D: [-10.0, 0.2, 0.2],
              pathPoints3D: [[-10.0, 0.2, 0.2], [-9.8, 4.0, 0.4], [-9.6, 7.5, 0.5], [-9.5, 10.0, 0.4]],
              bolts3D: [{ index: 1, position: [-9.8, 4.0, 0.4] }, { index: 2, position: [-9.6, 7.5, 0.5] }],
              anchor3D: [-9.5, 10.0, 0.4],
            },
            geometry2D: {
              routeId: 'route-pf-01',
              color: '#10B981',
              startPoint: { x: 0.10, y: 0.88 },
              pathPoints: [{ x: 0.10, y: 0.88 }, { x: 0.105, y: 0.70 }, { x: 0.11, y: 0.55 }],
              bolts: [{ index: 1, x: 0.105, y: 0.70 }],
              anchor: { x: 0.11, y: 0.55 },
            }
          },
          {
            id: 'route-pf-06',
            wallId: 'wall-pedra-furada',
            orderIndex: 2,
            name: 'Ilusão de Ótica',
            grade: { brazilian: 'V', french: '5b', yds: '5.8', danger: 'E1' },
            heightMeters: 20,
            pitchesCount: 1,
            boltsCount: 5,
            protectionType: 'chapeleta',
            anchorType: 'dupla_com_anel',
            style: 'esportiva',
            firstAscent: { climbers: ['Wolgrand Falcão', 'Emanoel Dupouy'], year: 2013 },
            description: 'Bonita via com um crux trabalhoso em agarras invertidas. Excelente para quem está iniciando e quer trabalhar o psicológico na condução de 5º grau.',
            geometry3D: {
              routeId: 'route-pf-06',
              color: '#3B82F6',
              tubeRadius: 0.05,
              startPoint3D: [-6.0, 0.2, 0.3],
              pathPoints3D: [[-6.0, 0.2, 0.3], [-5.8, 6.0, 0.6], [-5.5, 12.0, 0.9], [-5.3, 16.0, 0.8], [-5.0, 20.0, 0.6]],
              bolts3D: [
                { index: 1, position: [-5.9, 4.0, 0.5] },
                { index: 2, position: [-5.8, 8.0, 0.7] },
                { index: 3, position: [-5.6, 12.0, 0.9] },
                { index: 4, position: [-5.4, 16.0, 0.8] },
                { index: 5, position: [-5.2, 18.5, 0.7] },
              ],
              anchor3D: [-5.0, 20.0, 0.6],
            },
            geometry2D: {
              routeId: 'route-pf-06',
              color: '#3B82F6',
              startPoint: { x: 0.25, y: 0.90 },
              pathPoints: [{ x: 0.25, y: 0.90 }, { x: 0.26, y: 0.65 }, { x: 0.27, y: 0.40 }, { x: 0.28, y: 0.22 }],
              bolts: [{ index: 1, x: 0.255, y: 0.78 }, { index: 2, x: 0.265, y: 0.52 }, { index: 3, x: 0.275, y: 0.35 }],
              anchor: { x: 0.28, y: 0.22 },
            }
          },
          {
            id: 'route-pf-07',
            wallId: 'wall-pedra-furada',
            orderIndex: 3,
            name: 'Alívio Imediato',
            grade: { brazilian: 'VIIa', french: '6b', yds: '5.10c', danger: 'E1' },
            heightMeters: 25,
            pitchesCount: 1,
            boltsCount: 11,
            protectionType: 'chapeleta',
            rackRequired: 'Friend #1 opcional',
            anchorType: 'dupla_com_anel',
            style: 'esportiva',
            firstAscent: { climbers: ['Fabricio Leite', 'Ítalo Costa', 'Marlon Aronson', 'Rafael'], year: 2013 },
            description: 'Via muito bem protegida. Início técnico e crux exigente em uma barriguinha negativa. Depois segue mais tranquila por um diedro limpo até a parada dupla.',
            geometry3D: {
              routeId: 'route-pf-07',
              color: '#8B5CF6',
              tubeRadius: 0.05,
              startPoint3D: [-2.5, 0.2, 0.4],
              pathPoints3D: [[-2.5, 0.2, 0.4], [-2.3, 5.0, 0.8], [-2.0, 11.0, 1.4], [-1.8, 18.0, 1.2], [-1.5, 24.5, 0.8]],
              bolts3D: [
                { index: 1, position: [-2.4, 3.5, 0.6] },
                { index: 2, position: [-2.3, 7.0, 1.0] },
                { index: 3, position: [-2.1, 11.0, 1.4] },
                { index: 4, position: [-2.0, 14.5, 1.3] },
                { index: 5, position: [-1.8, 18.0, 1.2] },
                { index: 6, position: [-1.6, 21.5, 1.0] },
                { index: 7, position: [-1.5, 24.5, 0.8] },
              ],
              anchor3D: [-1.5, 24.5, 0.8],
            },
            geometry2D: {
              routeId: 'route-pf-07',
              color: '#8B5CF6',
              startPoint: { x: 0.38, y: 0.92 },
              pathPoints: [{ x: 0.38, y: 0.92 }, { x: 0.39, y: 0.68 }, { x: 0.41, y: 0.42 }, { x: 0.42, y: 0.16 }],
              bolts: [{ index: 1, x: 0.385, y: 0.78 }, { index: 2, x: 0.40, y: 0.55 }, { index: 3, x: 0.415, y: 0.30 }],
              anchor: { x: 0.42, y: 0.16 },
            }
          },
          {
            id: 'route-pf-10',
            wallId: 'wall-pedra-furada',
            orderIndex: 4,
            name: 'Turtle Roof',
            grade: { brazilian: 'IXa', french: '7c', yds: '5.12c', danger: 'E2' },
            heightMeters: 15,
            pitchesCount: 1,
            boltsCount: 9,
            protectionType: 'chapeleta',
            isProject: false,
            anchorType: 'dupla_com_anel',
            style: 'esportiva',
            firstAscent: { climbers: ['Cauí Vieira', 'Stenio Torres', 'Wolgrand Falcão'], year: 2013 },
            description: 'Via negativa brutal pelo teto da gruta com um lindo dinâmico no início e crux bem definido no final. Protegida com chapeletas e grampos de 1/2" na parada. Um dos tetos mais espetaculares do Nordeste!',
            safetyWarnings: 'Linha no teto com esforço hercúleo de antebraço e quedas limpas no vazio.',
            curiosities: 'O formato da rocha no topo lembra uma carapaça de tartaruga gigante.',
            geometry3D: {
              routeId: 'route-pf-10',
              color: '#EF4444', // Vermelho forte
              tubeRadius: 0.06,
              startPoint3D: [1.5, 0.2, 0.5],
              pathPoints3D: [[1.5, 0.2, 0.5], [1.8, 4.0, 1.2], [2.2, 8.5, 2.8], [2.5, 12.0, 3.4], [2.8, 15.0, 2.0]],
              bolts3D: [
                { index: 1, position: [1.6, 2.5, 0.8] },
                { index: 2, position: [1.8, 5.0, 1.5] },
                { index: 3, position: [2.0, 8.0, 2.5] },
                { index: 4, position: [2.3, 10.5, 3.2] },
                { index: 5, position: [2.5, 12.5, 3.4] },
                { index: 6, position: [2.7, 14.5, 2.3] },
                { index: 7, position: [2.8, 15.0, 2.0] },
              ],
              anchor3D: [2.8, 15.0, 2.0],
            },
            geometry2D: {
              routeId: 'route-pf-10',
              color: '#EF4444',
              startPoint: { x: 0.56, y: 0.94 },
              pathPoints: [{ x: 0.56, y: 0.94 }, { x: 0.58, y: 0.72 }, { x: 0.62, y: 0.50 }, { x: 0.65, y: 0.36 }],
              bolts: [{ index: 1, x: 0.57, y: 0.82 }, { index: 2, x: 0.59, y: 0.62 }, { index: 3, x: 0.63, y: 0.44 }],
              anchor: { x: 0.65, y: 0.36 },
            }
          },
          {
            id: 'route-pf-14',
            wallId: 'wall-pedra-furada',
            orderIndex: 5,
            name: 'Fogo na Babilônia',
            grade: { brazilian: 'VIIIb', french: '7b', yds: '5.12b', danger: 'E2' },
            heightMeters: 25,
            pitchesCount: 1,
            boltsCount: 13,
            protectionType: 'chapeleta',
            anchorType: 'corrente',
            style: 'esportiva',
            firstAscent: { climbers: ['Cauí Vieira', 'Fabricio Leite', 'Stenio Torres', 'Wolgrand Falcão'], year: 2013 },
            description: 'Via exigente no início (7b), seguindo por uma parte da parede muito lisa que na conquista fez-se em artificial (A0), e posteriormente encadenada integralmente em livre, subindo para VIIIb.',
            curiosities: 'Um dos grandes marcos da evolução do grau esportivo paraibano durante o EENe.',
            geometry3D: {
              routeId: 'route-pf-14',
              color: '#F59E0B',
              tubeRadius: 0.05,
              startPoint3D: [5.5, 0.2, 0.4],
              pathPoints3D: [[5.5, 0.2, 0.4], [5.8, 6.0, 0.9], [6.2, 13.0, 1.8], [6.5, 19.0, 1.4], [6.8, 25.0, 0.9]],
              bolts3D: [
                { index: 1, position: [5.6, 3.5, 0.6] },
                { index: 2, position: [5.8, 7.0, 1.0] },
                { index: 3, position: [6.0, 10.5, 1.5] },
                { index: 4, position: [6.2, 14.0, 1.8] },
                { index: 5, position: [6.4, 18.0, 1.5] },
                { index: 6, position: [6.6, 21.5, 1.2] },
                { index: 7, position: [6.8, 25.0, 0.9] },
              ],
              anchor3D: [6.8, 25.0, 0.9],
            },
            geometry2D: {
              routeId: 'route-pf-14',
              color: '#F59E0B',
              startPoint: { x: 0.74, y: 0.93 },
              pathPoints: [{ x: 0.74, y: 0.93 }, { x: 0.76, y: 0.68 }, { x: 0.78, y: 0.40 }, { x: 0.80, y: 0.15 }],
              bolts: [{ index: 1, x: 0.75, y: 0.80 }, { index: 2, x: 0.77, y: 0.54 }, { index: 3, x: 0.79, y: 0.28 }],
              anchor: { x: 0.80, y: 0.15 },
            }
          },
          {
            id: 'route-pf-16',
            wallId: 'wall-pedra-furada',
            orderIndex: 6,
            name: 'Capitão Caverna',
            grade: { brazilian: 'IV sup', french: '5a', yds: '5.7', danger: 'E1' },
            heightMeters: 15,
            pitchesCount: 1,
            boltsCount: 5,
            protectionType: 'chapeleta',
            anchorType: 'dupla_com_anel',
            style: 'esportiva',
            firstAscent: { climbers: ['Fabricio Leite', 'Fabio', 'Richard Macedo'], year: 2012 },
            description: 'Via muito gostosa na placa direita, bem protegida, agarras fartas e saída suave.',
            geometry3D: {
              routeId: 'route-pf-16',
              color: '#10B981',
              tubeRadius: 0.05,
              startPoint3D: [9.0, 0.2, 0.2],
              pathPoints3D: [[9.0, 0.2, 0.2], [9.2, 5.0, 0.4], [9.3, 10.0, 0.6], [9.5, 15.0, 0.5]],
              bolts3D: [{ index: 1, position: [9.1, 4.0, 0.3] }, { index: 2, position: [9.3, 9.0, 0.5] }, { index: 3, position: [9.4, 13.0, 0.5] }],
              anchor3D: [9.5, 15.0, 0.5],
            },
            geometry2D: {
              routeId: 'route-pf-16',
              color: '#10B981',
              startPoint: { x: 0.90, y: 0.92 },
              pathPoints: [{ x: 0.90, y: 0.92 }, { x: 0.91, y: 0.65 }, { x: 0.92, y: 0.38 }],
              bolts: [{ index: 1, x: 0.905, y: 0.75 }, { index: 2, x: 0.915, y: 0.52 }],
              anchor: { x: 0.92, y: 0.38 },
            }
          }
        ]
      },

      // PAREDE 2: PEDRA DO CABOCLO (O maior paredão de Algodão de Jandaíra - Face Sul até 70m)
      {
        id: 'wall-pedra-caboclo',
        sectorId: 'sector-algodao-jandaira',
        name: 'Pedra do Caboclo (Face Sul)',
        orientation: 'S',
        sunShadeNotes: 'Face Sul bem ventilada. Sol até o meio-dia, sombra à tarde.',
        sunExposure: {
          morning: 'sol',
          afternoon: 'sombra',
        },
        heightMeters: 65,
        rockType: 'granito',
        approachNotes: 'Estacionar na Casa do Seu Antônio e caminhar 10 minutos contornando a cerca até os totens de pedra da Face Sul.',
        history: 'O maior maciço de Algodão de Jandaíra, com linhas monumentais de até 70 metros de extensão em granito sólido e limpo.',
        fallbackPhotoUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
        photos: [
          {
            id: 'photo-pc-1',
            url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
            caption: 'Paredão maciço da Face Sul da Pedra do Caboclo',
            isMain: true,
          }
        ],
        // NÍVEL 2: CROQUI INTERATIVO 2D ATIVO
        activeTopo2D: {
          id: 'topo-pedra-caboclo-2d',
          wallId: 'wall-pedra-caboclo',
          imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
          width: 1200,
          height: 800,
          aspectRatio: 1.5,
          photographer: 'Emmanuel Dupouy / Adrieny Oliveira',
        },
        routes: [
          {
            id: 'route-pc-01',
            wallId: 'wall-pedra-caboclo',
            orderIndex: 1,
            name: 'Ressurreição Alucinante',
            grade: { brazilian: 'VI', french: '6a', yds: '5.10a', danger: 'E2' },
            heightMeters: 65,
            pitchesCount: 2,
            boltsCount: 2,
            protectionType: 'movel',
            rackRequired: '1 jogo de friends e 1 jogo de nuts',
            anchorType: 'parada_natural',
            style: 'tradicional',
            firstAscent: { climbers: ['Daniel Venancio', 'Claudionor Costa'], year: 2007 },
            description: 'Início com apenas dois grampos até a parada em móvel. Passa pela vegetação e entra na última enfiada crux em móvel na fenda até o bloco do cume. Não há rapel.',
            geometry2D: {
              routeId: 'route-pc-01',
              color: '#3B82F6',
              startPoint: { x: 0.15, y: 0.90 },
              pathPoints: [{ x: 0.15, y: 0.90 }, { x: 0.16, y: 0.60 }, { x: 0.17, y: 0.35 }, { x: 0.18, y: 0.12 }],
              bolts: [{ index: 1, x: 0.155, y: 0.75 }, { index: 2, x: 0.165, y: 0.50 }],
              anchor: { x: 0.18, y: 0.12 },
            }
          },
          {
            id: 'route-pc-03',
            wallId: 'wall-pedra-caboclo',
            orderIndex: 2,
            name: 'Vai dar Rock? Não! Vai dar Samba!',
            grade: { brazilian: 'VIIb', french: '6b+', yds: '5.10d', danger: 'E1' },
            heightMeters: 60,
            pitchesCount: 2,
            boltsCount: 15,
            protectionType: 'grampo',
            anchorType: 'dupla_com_anel',
            style: 'esportiva',
            firstAscent: { climbers: ['Fabrício Leite', 'Stenio Torres', 'Wolgrand Falcão'], year: 2013 },
            description: 'Linha ao lado da grande mancha vermelha. Grampeação de 1/2" em linha reta. Escala-se em até duas enfiadas com paradas duplas aos 30 e 60 metros.',
            geometry2D: {
              routeId: 'route-pc-03',
              color: '#8B5CF6',
              startPoint: { x: 0.32, y: 0.91 },
              pathPoints: [{ x: 0.32, y: 0.91 }, { x: 0.33, y: 0.62 }, { x: 0.34, y: 0.36 }, { x: 0.35, y: 0.10 }],
              bolts: [{ index: 1, x: 0.325, y: 0.76 }, { index: 2, x: 0.335, y: 0.50 }, { index: 3, x: 0.345, y: 0.25 }],
              anchor: { x: 0.35, y: 0.10 },
            }
          },
          {
            id: 'route-pc-07',
            wallId: 'wall-pedra-caboclo',
            orderIndex: 3,
            name: 'Amnésia na Chapa',
            grade: { brazilian: 'VIIc', french: '6c', yds: '5.11a', danger: 'E1' },
            heightMeters: 60,
            pitchesCount: 2,
            boltsCount: 15,
            protectionType: 'chapeleta',
            anchorType: 'dupla_com_anel',
            style: 'esportiva',
            firstAscent: { climbers: ['Fabricio Leite', 'Dagoberto Ivan', 'Rafael', 'Stenio Torres'], year: 2011 },
            description: 'Via técnica de alta qualidade, lances finos de pé-mão com crux no meio da falésia. Chapeletas e grampos de 1/2" nas paradas de rapel.',
            geometry2D: {
              routeId: 'route-pc-07',
              color: '#EC4899',
              startPoint: { x: 0.52, y: 0.92 },
              pathPoints: [{ x: 0.52, y: 0.92 }, { x: 0.53, y: 0.64 }, { x: 0.54, y: 0.38 }, { x: 0.55, y: 0.11 }],
              bolts: [{ index: 1, x: 0.525, y: 0.78 }, { index: 2, x: 0.535, y: 0.52 }, { index: 3, x: 0.545, y: 0.26 }],
              anchor: { x: 0.55, y: 0.11 },
            }
          },
          {
            id: 'route-pc-09',
            wallId: 'wall-pedra-caboclo',
            orderIndex: 4,
            name: 'João Grandão',
            grade: { brazilian: 'IV', french: '4c', yds: '5.6', danger: 'E1' },
            heightMeters: 65,
            pitchesCount: 2,
            boltsCount: 10,
            protectionType: 'grampo',
            anchorType: 'dupla_com_anel',
            style: 'esportiva',
            firstAscent: { climbers: ['Ítalo Costa', 'João Ribeiro', 'Wolgrand Falcão'], year: 2011 },
            description: 'Escalada deliciosa e muito fácil com agarras gigantescas em rocha super sólida. Excelente para quem está começando nas paredes longas.',
            geometry2D: {
              routeId: 'route-pc-09',
              color: '#10B981',
              startPoint: { x: 0.68, y: 0.91 },
              pathPoints: [{ x: 0.68, y: 0.91 }, { x: 0.69, y: 0.63 }, { x: 0.70, y: 0.36 }, { x: 0.71, y: 0.12 }],
              bolts: [{ index: 1, x: 0.685, y: 0.77 }, { index: 2, x: 0.695, y: 0.50 }],
              anchor: { x: 0.71, y: 0.12 },
            }
          },
          {
            id: 'route-pc-11',
            wallId: 'wall-pedra-caboclo',
            orderIndex: 5,
            name: 'Mar de Agarras',
            grade: { brazilian: 'IV sup', french: '5a', yds: '5.7', danger: 'E1' },
            heightMeters: 60,
            pitchesCount: 2,
            boltsCount: 10,
            protectionType: 'grampo',
            anchorType: 'dupla_com_anel',
            style: 'esportiva',
            firstAscent: { climbers: ['Fabrício Leite', 'Dagoberto Ivan', 'Rafael'], year: 2011 },
            description: 'Como o próprio nome diz, agarra não é problema! Uma das mais clássicas e tranquilas do setor.',
            geometry2D: {
              routeId: 'route-pc-11',
              color: '#38BDF8',
              startPoint: { x: 0.82, y: 0.91 },
              pathPoints: [{ x: 0.82, y: 0.91 }, { x: 0.83, y: 0.62 }, { x: 0.84, y: 0.35 }, { x: 0.85, y: 0.14 }],
              bolts: [{ index: 1, x: 0.825, y: 0.75 }, { index: 2, x: 0.835, y: 0.48 }],
              anchor: { x: 0.85, y: 0.14 },
            }
          }
        ]
      },

      // PAREDE 3: SETOR MIRANTE (Predomínio de Móvel e Face Norte)
      {
        id: 'wall-mirante',
        sectorId: 'sector-algodao-jandaira',
        name: 'Setor Mirante (Face Norte)',
        orientation: 'N',
        sunShadeNotes: 'Face Norte. Sol pela manhã até as 11h. Sombra à tarde.',
        sunExposure: {
          morning: 'sol',
          afternoon: 'sombra',
        },
        heightMeters: 40,
        rockType: 'granito',
        approachNotes: 'Estrada sentido Pedra Furada, entrada na casa de Toinho e caminhada de 800m.',
        history: 'Setor com grande predominância de vias em proteção móvel clássica de 35 a 40 metros.',
        fallbackPhotoUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
        photos: [
          {
            id: 'photo-mirante-1',
            url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
            caption: 'Face Norte do Setor Mirante com suas fendas marcantes',
            isMain: true,
          }
        ],
        routes: [
          {
            id: 'route-mirante-01',
            wallId: 'wall-mirante',
            orderIndex: 1,
            name: 'Flores do Campo',
            grade: { brazilian: 'V sup', french: '5c', yds: '5.9', danger: 'E2' },
            heightMeters: 40,
            pitchesCount: 1,
            boltsCount: 0,
            protectionType: 'movel',
            rackRequired: 'Nuts BD #4 cinza, #9 azul, #12 verde, #13 red; Camalot #.3 à #4; friends RockEmpire #6 e #7',
            anchorType: 'parada_natural',
            style: 'tradicional',
            firstAscent: { climbers: ['Fabricio Leite', 'Stenio Torres', 'Wolgrand Falcão'], year: 2013 },
            description: 'Via 100% em móvel! Começa em um diedro positivo de 4º grau e crux de uma passada saindo do diedro. Parada natural em árvore.',
          },
          {
            id: 'route-mirante-02',
            wallId: 'wall-mirante',
            orderIndex: 2,
            name: 'Monstros e Vermes',
            grade: { brazilian: 'VI sup', french: '6a+', yds: '5.10b', danger: 'E1' },
            heightMeters: 30,
            pitchesCount: 1,
            boltsCount: 13,
            protectionType: 'chapeleta',
            anchorType: 'dupla_com_anel',
            style: 'esportiva',
            firstAscent: { climbers: ['Fabricio Leite', 'Stenio Torres', 'Wolgrand Falcão', 'Emanoel Dupouy'], year: 2013 },
            description: 'Exigente com crux bem vertical em regletes finos, depois pega a parede mais positiva até a parada dupla.',
          },
          {
            id: 'route-mirante-05',
            wallId: 'wall-mirante',
            orderIndex: 3,
            name: 'Entre Amigos',
            grade: { brazilian: 'VI sup', french: '6a+', yds: '5.10b', danger: 'E1' },
            heightMeters: 40,
            pitchesCount: 1,
            boltsCount: 13,
            protectionType: 'chapeleta',
            anchorType: 'dupla_com_anel',
            style: 'esportiva',
            firstAscent: { climbers: ['Fabricio Leite', 'Emanoel Dupouy', 'Wolgrand Falcão'], year: 2013 },
            description: 'Começa com uma viradinha do negativo para o vertical que é o crux, depois pega na continuidade bem movimentada.',
          },
          {
            id: 'route-mirante-07',
            wallId: 'wall-mirante',
            orderIndex: 4,
            name: 'Cupim Atômico',
            grade: { brazilian: 'V', french: '5b', yds: '5.8', danger: 'E2' },
            heightMeters: 30,
            pitchesCount: 1,
            boltsCount: 0,
            protectionType: 'movel',
            rackRequired: '1 jogo Camalot C4 do #.3 ao #3, 1 jogo Camalot C3, Nuts médios',
            anchorType: 'parada_natural',
            style: 'tradicional',
            firstAscent: { climbers: ['Ary Pacheco Neto', 'Stenio Torres'], year: 2013 },
            description: 'Única via dentro da Grota no Mirante, sem proteção fixa, vertical bastante fraturado cheio de fendas.',
          }
        ]
      }
    ]
  },

  // SETOR 2: SERRA DO CIPÓ (MG)
  {
    id: 'sector-cipo-olhos',
    name: 'Falésia dos Olhos',
    cragName: 'Serra do Cipó',
    region: 'Cordilheira do Espinhaço',
    city: 'Santana do Riacho',
    state: 'MG',
    coordinates: {
      latitude: -19.2891,
      longitude: -43.5284,
    },
    elevationMeters: 1150,
    approachTimeMinutes: 25,
    approachTrailDescription: 'Trilha moderada a partir da Pousada Monjolos. Seguir os totens de pedra até a base da falésia de calcário.',
    accessStatus: 'aberto',
    history: 'Um dos setores mais emblemáticos do Brasil, aberto no início dos anos 90.',
    walls: [
      {
        id: 'wall-olhos-principal',
        sectorId: 'sector-cipo-olhos',
        name: 'Paredão dos Olhos (MG)',
        orientation: 'SE',
        sunShadeNotes: 'Sol até as 11h30. Sombra fresca à tarde.',
        sunExposure: { morning: 'sol', afternoon: 'sombra' },
        heightMeters: 28,
        rockType: 'calcario',
        approachNotes: 'Parede principal do grande teto.',
        fallbackPhotoUrl: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1200&q=80',
        photos: [{ id: 'p1', url: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1200&q=80', isMain: true }],
        routes: [
          {
            id: 'route-vitamina-a',
            wallId: 'wall-olhos-principal',
            orderIndex: 1,
            name: 'Vitamina A',
            grade: { brazilian: '6º sup', french: '6a', yds: '5.10b', danger: 'E1' },
            heightMeters: 18,
            pitchesCount: 1,
            boltsCount: 8,
            protectionType: 'chapeleta',
            anchorType: 'dupla_com_anel',
            style: 'esportiva',
            description: 'Clássica via em regletes positivos e barriga suave com pegadas cavadas excelentes.',
          }
        ]
      }
    ]
  }
];

export const INITIAL_LOGBOOK_ENTRIES = [
  {
    id: 'log-1',
    routeId: 'route-pf-10',
    routeName: 'Turtle Roof',
    wallName: 'Pedra Furada (Face Leste)',
    sectorName: 'Algodão de Jandaíra (PB)',
    gradeStr: 'IXa',
    date: '2026-09-10',
    style: 'redpoint' as const,
    ratingStars: 5 as const,
    personalNotes: 'Que teto absurdo! O dinâmico no início é lindo e a saída na carapaça exige muita técnica de calcanhar.',
    partner: 'Cauí Vieira',
  },
  {
    id: 'log-2',
    routeId: 'route-pf-07',
    routeName: 'Alívio Imediato',
    wallName: 'Pedra Furada (Face Leste)',
    sectorName: 'Algodão de Jandaíra (PB)',
    gradeStr: 'VIIa',
    date: '2026-09-08',
    style: 'onsight' as const,
    ratingStars: 5 as const,
    personalNotes: 'À vista perfeita! A barriguinha negativa é o crux, depois o diedro flui muito bem.',
    partner: 'Wolgrand Falcão',
  }
];

// LISTA DE POLOS / DESTINOS DE ESCALADA PARA A TELA INICIAL
export const CLIMBING_DESTINATIONS: ClimbingDestination[] = [
  {
    id: 'dest-algodao-jandaira',
    name: 'Algodão de Jandaíra',
    state: 'PB',
    regionName: 'Curimataú Ocidental',
    coverImage: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1200&q=80',
    description: 'Sede histórica do XII EENe 2013. O paraíso do granito claro no Nordeste, com paredes de até 70m, fendas clássicas em móvel e tetos negativos como a mítica Pedra Furada.',
    rockType: 'Granito Claro',
    totalRoutes: 90,
    totalSectors: 6,
    has3D: true,
    hasTrad: true,
    hasSport: true,
    hasBoulder: true,
    distanceFromCapital: '200 km de João Pessoa • 70 km de Campina Grande • 14 km de Remígio',
    highlights: ['Pedra Furada (3D & Teto Negativo)', 'Pedra do Caboclo (Paredão 70m)', 'Setor Mirante (Móvel Clássico)', 'Setor Climatizado'],
    sectors: [MOCK_SECTORS[0]],
  },
  {
    id: 'dest-campina-grande',
    name: 'Campina Grande',
    state: 'PB',
    regionName: 'Agreste Paraibano',
    coverImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    description: 'Um dos grandes berços da escalada paraibana. Destaque para a famosa Pedra do Marinho e o Parque do Poeta, com vias esportivas técnicas em placas de granito e blocos de boulder.',
    rockType: 'Granito & Gnaisse',
    totalRoutes: 45,
    totalSectors: 3,
    has3D: false,
    hasTrad: true,
    hasSport: true,
    hasBoulder: true,
    distanceFromCapital: '130 km de João Pessoa',
    highlights: ['Pedra do Marinho', 'Parque do Poeta', 'Boulders de Bodocongó'],
    sectors: [
      {
        id: 'sector-cg-marinho',
        name: 'Pedra do Marinho',
        cragName: 'Polo de Campina Grande',
        region: 'Agreste Paraibano',
        city: 'Campina Grande',
        state: 'PB',
        coordinates: { latitude: -7.2307, longitude: -35.8811 },
        elevationMeters: 550,
        approachTimeMinutes: 15,
        approachTrailDescription: 'Acesso fácil por estrada asfaltada e trilha curta sinalizada até a base das placas de granito.',
        accessStatus: 'aberto',
        walls: [
          {
            id: 'wall-cg-marinho-leste',
            sectorId: 'sector-cg-marinho',
            name: 'Placa Principal do Marinho',
            orientation: 'L',
            sunShadeNotes: 'Sol pela manhã, sombra a partir das 12h.',
            sunExposure: { morning: 'sol', afternoon: 'sombra' },
            heightMeters: 22,
            rockType: 'granito',
            approachNotes: 'Base ampla com sombra de árvores.',
            fallbackPhotoUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
            photos: [{ id: 'p-cg', url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80', isMain: true }],
            routes: [
              {
                id: 'route-cg-1',
                wallId: 'wall-cg-marinho-leste',
                orderIndex: 1,
                name: 'Vento Nordestino',
                grade: { brazilian: '6º', french: '6a', yds: '5.10a', danger: 'E1' },
                heightMeters: 20,
                pitchesCount: 1,
                boltsCount: 7,
                protectionType: 'chapeleta',
                anchorType: 'dupla_com_anel',
                style: 'esportiva',
                description: 'Linha técnica de equilíbrio e boa leitura de pés em granito aderente.',
              },
              {
                id: 'route-cg-2',
                wallId: 'wall-cg-marinho-leste',
                orderIndex: 2,
                name: 'Asa Branca',
                grade: { brazilian: '7a', french: '6b', yds: '5.10c', danger: 'E1' },
                heightMeters: 22,
                pitchesCount: 1,
                boltsCount: 9,
                protectionType: 'chapeleta',
                anchorType: 'corrente',
                style: 'esportiva',
                description: 'Passagem fina no terço médio sobre regletes horizontais pequenos.',
              }
            ]
          }
        ]
      }
    ],
  },
  {
    id: 'dest-sousa',
    name: 'Sousa',
    state: 'PB',
    regionName: 'Alto Sertão Paraibano',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    description: 'Terra dos Dinossauros e dos inselbergues do Sertão. Paredes com excelente potencial para vias tradicionais e esportivas em rocha esculpida pelo vento semiárido.',
    rockType: 'Arenito & Granito',
    totalRoutes: 25,
    totalSectors: 2,
    has3D: false,
    hasTrad: true,
    hasSport: true,
    hasBoulder: false,
    distanceFromCapital: '430 km de João Pessoa • 310 km de Campina Grande',
    highlights: ['Inselbergues do Sertão', 'Serrote do Feiticeiro', 'Placas do Vale dos Dinossauros'],
    sectors: [
      {
        id: 'sector-sousa-sertao',
        name: 'Serrote do Feiticeiro',
        cragName: 'Polo do Alto Sertão',
        region: 'Alto Sertão Paraibano',
        city: 'Sousa',
        state: 'PB',
        coordinates: { latitude: -6.7608, longitude: -38.2325 },
        elevationMeters: 410,
        approachTimeMinutes: 20,
        approachTrailDescription: 'Caminhada na caatinga a partir da estrada vicinal do Vale dos Dinossauros.',
        accessStatus: 'aberto',
        walls: [
          {
            id: 'wall-sousa-feiticeiro',
            sectorId: 'sector-sousa-sertao',
            name: 'Paredão do Sertão',
            orientation: 'E',
            sunShadeNotes: 'Sol pela manhã bem cedo. Sombra garantida a partir das 11h.',
            sunExposure: { morning: 'sol', afternoon: 'sombra' },
            heightMeters: 30,
            rockType: 'granito',
            approachNotes: 'Base plana cercada por cactos e vegetação típica.',
            fallbackPhotoUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
            photos: [{ id: 'p-sousa', url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80', isMain: true }],
            routes: [
              {
                id: 'route-sousa-1',
                wallId: 'wall-sousa-feiticeiro',
                orderIndex: 1,
                name: 'Pegada de T-Rex',
                grade: { brazilian: '6º sup', french: '6a+', yds: '5.10b', danger: 'E1' },
                heightMeters: 25,
                pitchesCount: 1,
                boltsCount: 8,
                protectionType: 'chapeleta',
                anchorType: 'dupla_com_anel',
                style: 'esportiva',
                description: 'Início em buracos cavados generosos, culminando numa fenda diagonal sólida.',
              },
              {
                id: 'route-sousa-2',
                wallId: 'wall-sousa-feiticeiro',
                orderIndex: 2,
                name: 'Calor do Sertão',
                grade: { brazilian: '7b', french: '6b+', yds: '5.10d', danger: 'E2' },
                heightMeters: 28,
                pitchesCount: 1,
                boltsCount: 10,
                protectionType: 'chapeleta',
                anchorType: 'corrente',
                style: 'esportiva',
                description: 'Via exigente de resistência em placa vertical contínua.',
              }
            ]
          }
        ]
      }
    ],
  },
  {
    id: 'dest-araruna',
    name: 'Araruna (Pedra da Boca)',
    state: 'PB',
    regionName: 'Curimataú / Agreste',
    coverImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
    description: 'O Parque Estadual da Pedra da Boca é um dos maiores monumentos de escalada do Brasil. Paredões vertiginosos de até 250 metros em granito liso, chaminés e tetos gigantes.',
    rockType: 'Granito & Gnaisse',
    totalRoutes: 80,
    totalSectors: 5,
    has3D: false,
    hasTrad: true,
    hasSport: true,
    hasBoulder: true,
    distanceFromCapital: '165 km de João Pessoa • 95 km de Algodão de Jandaíra',
    highlights: ['Pedra da Boca (Grande Maciço)', 'Pedra do Letreiro', 'Pedra da Santa'],
    sectors: [
      {
        id: 'sector-araruna-boca',
        name: 'Pedra da Boca (Maciço Principal)',
        cragName: 'Parque Estadual da Pedra da Boca',
        region: 'Curimataú',
        city: 'Araruna',
        state: 'PB',
        coordinates: { latitude: -6.4522, longitude: -35.6811 },
        elevationMeters: 620,
        approachTimeMinutes: 20,
        approachTrailDescription: 'Trilha do Parque Estadual a partir da Pousada do Seu Tico.',
        accessStatus: 'aberto',
        walls: [
          {
            id: 'wall-araruna-principal',
            sectorId: 'sector-araruna-boca',
            name: 'Paredão da Pedra da Boca',
            orientation: 'S',
            sunShadeNotes: 'Face sombreada em boa parte do dia.',
            sunExposure: { morning: 'sombra', afternoon: 'sol' },
            heightMeters: 120,
            rockType: 'granito',
            approachNotes: 'Caminhada clássica pela trilha principal do parque.',
            fallbackPhotoUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
            photos: [{ id: 'p-pboca', url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80', isMain: true }],
            routes: [
              {
                id: 'route-boca-1',
                wallId: 'wall-araruna-principal',
                orderIndex: 1,
                name: 'Via dos Cristais',
                grade: { brazilian: '5º sup', french: '5c', yds: '5.9', danger: 'E1' },
                heightMeters: 60,
                pitchesCount: 2,
                boltsCount: 12,
                protectionType: 'grampo',
                anchorType: 'dupla_com_anel',
                style: 'esportiva',
                description: 'Escalada clássica da Pedra da Boca com excelente aderência em quartzo.',
              }
            ]
          }
        ]
      }
    ],
  },
  {
    id: 'dest-caja-banguelo',
    name: 'Cajá / Mogeiro (Pedra do Banguelo)',
    state: 'PB',
    regionName: 'Vale do Paraíba',
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80',
    description: 'Lar da imponente Pedra do Banguelo, visível da rodovia BR-230. Escaladas clássicas de várias enfiadas em rocha sólida.',
    rockType: 'Granito',
    totalRoutes: 20,
    totalSectors: 1,
    has3D: false,
    hasTrad: true,
    hasSport: true,
    hasBoulder: false,
    distanceFromCapital: '88 km de João Pessoa • 45 km de Campina Grande',
    highlights: ['Pedra do Banguelo', 'Face Nordeste'],
    sectors: [
      {
        id: 'sector-banguelo',
        name: 'Pedra do Banguelo',
        cragName: 'Polo do Cajá',
        region: 'Vale do Paraíba',
        city: 'Cajá / Mogeiro',
        state: 'PB',
        coordinates: { latitude: -7.2891, longitude: -35.4312 },
        elevationMeters: 380,
        approachTimeMinutes: 25,
        approachTrailDescription: 'Subida em trilha de pasto a partir da entrada da fazenda.',
        accessStatus: 'aberto',
        walls: [
          {
            id: 'wall-banguelo-leste',
            sectorId: 'sector-banguelo',
            name: 'Face Leste do Banguelo',
            orientation: 'L',
            sunShadeNotes: 'Sol pela manhã, sombra à tarde.',
            sunExposure: { morning: 'sol', afternoon: 'sombra' },
            heightMeters: 50,
            rockType: 'granito',
            approachNotes: 'Base com pedras soltas, atenção.',
            fallbackPhotoUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80',
            photos: [{ id: 'p-bang', url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80', isMain: true }],
            routes: [
              {
                id: 'route-bang-1',
                wallId: 'wall-banguelo-leste',
                orderIndex: 1,
                name: 'Directa do Banguelo',
                grade: { brazilian: '6º', french: '6a', yds: '5.10a', danger: 'E1' },
                heightMeters: 45,
                pitchesCount: 2,
                boltsCount: 10,
                protectionType: 'grampo',
                anchorType: 'dupla_com_anel',
                style: 'esportiva',
                description: 'Linha elegante que corta o centro da face.',
              }
            ]
          }
        ]
      }
    ],
  },
  {
    id: 'dest-serra-caiada',
    name: 'Serra Caiada',
    state: 'RN',
    regionName: 'Agreste Potiguar',
    coverImage: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80',
    description: 'Principal polo de escalada do Rio Grande do Norte. Paredes de granito com vias esportivas bem protegidas e comunidade ativa.',
    rockType: 'Granito',
    totalRoutes: 65,
    totalSectors: 4,
    has3D: false,
    hasTrad: true,
    hasSport: true,
    hasBoulder: true,
    distanceFromCapital: '80 km de Natal • 160 km de Algodão de Jandaíra',
    highlights: ['Face Leste', 'Setor da Igreja', 'Boulders da Base'],
    sectors: [
      {
        id: 'sector-serra-caiada-principal',
        name: 'Face Leste de Serra Caiada',
        cragName: 'Serra Caiada',
        region: 'Agreste Potiguar',
        city: 'Serra Caiada',
        state: 'RN',
        coordinates: { latitude: -6.1105, longitude: -35.7142 },
        elevationMeters: 320,
        approachTimeMinutes: 10,
        approachTrailDescription: 'Acesso imediato pela rodovia com 10 minutos de caminhada.',
        accessStatus: 'aberto',
        walls: [
          {
            id: 'wall-caiada-leste',
            sectorId: 'sector-serra-caiada-principal',
            name: 'Paredão Central',
            orientation: 'L',
            sunShadeNotes: 'Sol pela manhã, sombra fresca após o meio-dia.',
            sunExposure: { morning: 'sol', afternoon: 'sombra' },
            heightMeters: 28,
            rockType: 'granito',
            approachNotes: 'Base confortável e arborizada.',
            fallbackPhotoUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80',
            photos: [{ id: 'p-caiada', url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80', isMain: true }],
            routes: [
              {
                id: 'route-caiada-1',
                wallId: 'wall-caiada-leste',
                orderIndex: 1,
                name: 'Potiguar',
                grade: { brazilian: '6º', french: '6a', yds: '5.10a', danger: 'E1' },
                heightMeters: 25,
                pitchesCount: 1,
                boltsCount: 8,
                protectionType: 'chapeleta',
                anchorType: 'dupla_com_anel',
                style: 'esportiva',
                description: 'Aderência perfeita com ótimas agarras.',
              }
            ]
          }
        ]
      }
    ],
  },
  {
    id: 'dest-serra-cipo',
    name: 'Serra do Cipó',
    state: 'MG',
    regionName: 'Cordilheira do Espinhaço',
    coverImage: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1200&q=80',
    description: 'A meca da escalada esportiva no calcário brasileiro. Paredões imponentes, regletes finos e grandes tetos negativos.',
    rockType: 'Calcário',
    totalRoutes: 350,
    totalSectors: 12,
    has3D: true,
    hasTrad: false,
    hasSport: true,
    hasBoulder: false,
    distanceFromCapital: '100 km de Belo Horizonte',
    highlights: ['Falésia dos Olhos', 'Setor Gafanhoto', 'Vale da Serra'],
    sectors: [MOCK_SECTORS[1]],
  }
];

