// Dados Mocks de Falésias e Paredes Brasileiras
import { Sector, Wall, Route } from '../types/climbing';

export const MOCK_SECTORS: Sector[] = [
  {
    id: 'sector-cipo-olhos',
    name: 'Falésia dos Olhos',
    cragName: 'Serra do Cipó',
    region: 'Cordilheira do Espinhaço',
    city: 'Santana do Riacho',
    state: 'MG',
    coordinates: {
      latitude: -19.2891,
      longitude: -43.5284,
    },
    elevationMeters: 1150,
    approachTimeMinutes: 25,
    approachTrailDescription: 'Trilha moderada a partir da Pousada Monjolos. Seguir os totens de pedra até a base da falésia de calcário.',
    accessStatus: 'aberto',
    accessNotes: 'Taxa de preservação de R$ 10 paga na guarita comunitária da ACMG. Leve todo seu lixo de volta.',
    history: 'Um dos setores mais emblemáticos do Brasil, aberto no início dos anos 90 por escaladores mineiros e brasilienses. Famoso pelas vias de agarras e regletes em calcário de altíssima aderência.',
    rules: [
      'Proibido fogueiras na base da falésia',
      'Uso de capacete recomendado para o segurador',
      'Descer pelas paradas duplas com anel; não faça top-rope diretamente na chapeleta',
    ],
    walls: [
      {
        id: 'wall-olhos-principal',
        sectorId: 'sector-cipo-olhos',
        name: 'Paredão Principal (Olhos)',
        orientation: 'SE',
        sunShadeNotes: 'Sol até as 11h30. Sombra fresca e vento suave durante toda a tarde.',
        heightMeters: 28,
        rockType: 'calcario',
        approachNotes: 'Logo na chegada da trilha, a parede principal é a que possui o grande teto com fendas.',
        history: 'Conquistada entre 1994 e 1998 por André Berezowski, Ralf Flores e companheiros.',
        fallbackPhotoUrl: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1200&q=80',
        photos: [
          {
            id: 'photo-1',
            url: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1200&q=80',
            caption: 'Vista frontal do Paredão Principal ao entardecer',
            photographer: 'Julio Cesar',
            isMain: true,
          }
        ],
        // NÍVEL 1: MODELO 3D REAL DA PAREDE DISPONÍVEL!
        model3D: {
          id: 'model-olhos-3d',
          wallId: 'wall-olhos-principal',
          isProceduralMesh: true,
          dimensionsMeters: {
            width: 26,
            height: 28,
            depth: 7,
          },
          cameraPresets: {
            initialPosition: [0, 8, 26],
            target: [0, 10, 0],
            minDistance: 8,
            maxDistance: 45,
          },
          meshPolyCount: 48000,
          photogrammetrySource: {
            photoCount: 240,
            resolution: '4K PBR',
            dateCaptured: '2024-05-18',
          }
        },
        routes: [
          {
            id: 'route-vitamina-a',
            wallId: 'wall-olhos-principal',
            orderIndex: 1,
            name: 'Vitamina A',
            grade: {
              brazilian: '6º sup',
              french: '6a',
              yds: '5.10b',
              danger: 'E1',
            },
            heightMeters: 18,
            pitchesCount: 1,
            boltsCount: 8,
            anchorType: 'dupla_com_anel',
            style: 'esportiva',
            firstAscent: {
              climbers: ['Ralf Flores', 'Marcos Castro'],
              year: 1995,
            },
            bolters: {
              names: ['Ralf Flores'],
              year: 1995,
              hardwareNotes: 'Chapeletas Fixe de aço inox 316L, 10mm',
            },
            description: 'Uma das vias de aquecimento mais clássicas da Serra do Cipó. Início vertical em regletes positivos, seguido por uma barriga suave com pegadas cavadas excelentes.',
            safetyWarnings: 'Primeira chapa a 3 metros do chão; recomenda-se usar vara de clipar para segurança do primeiro grampo.',
            curiosities: 'Batizada de Vitamina A porque todos os escaladores tomavam um sol matinal antes de encarar as vias do teto.',
            // Geometria 3D no espaço da rocha
            geometry3D: {
              routeId: 'route-vitamina-a',
              color: '#10B981', // Verde esmeralda
              tubeRadius: 0.05,
              startPoint3D: [-6.5, 0.2, 0.3],
              pathPoints3D: [
                [-6.5, 0.2, 0.3],
                [-6.3, 3.2, 0.6],
                [-6.0, 6.8, 0.8],
                [-5.8, 10.5, 1.1],
                [-5.6, 14.2, 0.9],
                [-5.5, 18.0, 0.5],
              ],
              bolts3D: [
                { index: 1, position: [-6.3, 3.2, 0.6] },
                { index: 2, position: [-6.1, 5.2, 0.7] },
                { index: 3, position: [-6.0, 7.8, 0.9] },
                { index: 4, position: [-5.9, 10.5, 1.1] },
                { index: 5, position: [-5.8, 12.8, 1.0] },
                { index: 6, position: [-5.6, 14.5, 0.9] },
                { index: 7, position: [-5.5, 16.5, 0.7] },
                { index: 8, position: [-5.5, 18.0, 0.5] },
              ],
              anchor3D: [-5.5, 18.0, 0.5],
            },
            // Geometria 2D fallback se o usuário alternar para modo 2D
            geometry2D: {
              routeId: 'route-vitamina-a',
              color: '#10B981',
              startPoint: { x: 0.18, y: 0.92 },
              pathPoints: [
                { x: 0.18, y: 0.92 },
                { x: 0.20, y: 0.75 },
                { x: 0.22, y: 0.58 },
                { x: 0.23, y: 0.42 },
                { x: 0.24, y: 0.28 },
              ],
              bolts: [
                { index: 1, x: 0.19, y: 0.82 },
                { index: 2, x: 0.20, y: 0.72 },
                { index: 3, x: 0.21, y: 0.62 },
                { index: 4, x: 0.22, y: 0.52 },
                { index: 5, x: 0.23, y: 0.42 },
                { index: 6, x: 0.24, y: 0.32 },
              ],
              anchor: { x: 0.24, y: 0.28 },
            },
          },
          {
            id: 'route-gis',
            wallId: 'wall-olhos-principal',
            orderIndex: 2,
            name: 'Gis',
            grade: {
              brazilian: '7a',
              french: '6b',
              yds: '5.10c',
              danger: 'E1',
            },
            heightMeters: 22,
            pitchesCount: 1,
            boltsCount: 10,
            anchorType: 'dupla_com_anel',
            style: 'esportiva',
            firstAscent: {
              climbers: ['André Berezowski'],
              year: 1996,
            },
            bolters: {
              names: ['André Berezowski', 'Ralf Flores'],
              year: 1996,
            },
            description: 'Via técnica de placa levemente negativa. Exige excelente trabalho de pés e leitura atenta de regletes afiados.',
            safetyWarnings: 'Crux na 4ª costura; proteções seguras e sem risco de bater em platô.',
            curiosities: 'O nome surgiu porque no dia da cadena o magnésio de todos os escaladores havia caído da mochila.',
            geometry3D: {
              routeId: 'route-gis',
              color: '#8B5CF6', // Roxo vibrante
              tubeRadius: 0.05,
              startPoint3D: [-2.0, 0.2, 0.4],
              pathPoints3D: [
                [-2.0, 0.2, 0.4],
                [-1.8, 4.0, 0.8],
                [-1.5, 8.5, 1.4],
                [-1.2, 13.0, 1.8],
                [-1.0, 17.5, 1.6],
                [-0.8, 22.0, 1.1],
              ],
              bolts3D: [
                { index: 1, position: [-1.9, 3.5, 0.7] },
                { index: 2, position: [-1.7, 6.0, 1.0] },
                { index: 3, position: [-1.6, 8.5, 1.4] },
                { index: 4, position: [-1.4, 11.0, 1.6] },
                { index: 5, position: [-1.2, 13.0, 1.8] },
                { index: 6, position: [-1.1, 15.5, 1.7] },
                { index: 7, position: [-1.0, 17.5, 1.6] },
                { index: 8, position: [-0.9, 19.8, 1.3] },
                { index: 9, position: [-0.8, 21.0, 1.2] },
                { index: 10, position: [-0.8, 22.0, 1.1] },
              ],
              anchor3D: [-0.8, 22.0, 1.1],
            },
            geometry2D: {
              routeId: 'route-gis',
              color: '#8B5CF6',
              startPoint: { x: 0.42, y: 0.94 },
              pathPoints: [
                { x: 0.42, y: 0.94 },
                { x: 0.43, y: 0.74 },
                { x: 0.45, y: 0.54 },
                { x: 0.46, y: 0.35 },
                { x: 0.47, y: 0.18 },
              ],
              bolts: [
                { index: 1, x: 0.42, y: 0.84 },
                { index: 2, x: 0.43, y: 0.74 },
                { index: 3, x: 0.44, y: 0.64 },
                { index: 4, x: 0.45, y: 0.54 },
                { index: 5, x: 0.46, y: 0.44 },
                { index: 6, x: 0.46, y: 0.35 },
                { index: 7, x: 0.47, y: 0.26 },
                { index: 8, x: 0.47, y: 0.18 },
              ],
              anchor: { x: 0.47, y: 0.18 },
            },
          },
          {
            id: 'route-super-heroi',
            wallId: 'wall-olhos-principal',
            orderIndex: 3,
            name: 'Super Herói',
            grade: {
              brazilian: '8b',
              french: '7a',
              yds: '5.11c',
              danger: 'E2',
            },
            heightMeters: 26,
            pitchesCount: 1,
            boltsCount: 12,
            anchorType: 'corrente',
            style: 'esportiva',
            firstAscent: {
              climbers: ['Cesar Grosso'],
              year: 2002,
            },
            bolters: {
              names: ['Ralf Flores', 'André Berezowski'],
              year: 1997,
            },
            description: 'Obra de arte da escalada esportiva brasileira. Atravessa um grande teto com batidas longas em pinças e abaulados, finalizando numa placa vertiginosa exposta ao vazio.',
            safetyWarnings: 'Voos longos no teto. Certifique-se de que a corda tem pelo menos 60 metros.',
            curiosities: 'Considerada uma das vias mais estéticas e fotogênicas do estado de Minas Gerais.',
            geometry3D: {
              routeId: 'route-super-heroi',
              color: '#F59E0B', // Âmbar
              tubeRadius: 0.05,
              startPoint3D: [2.5, 0.2, 0.5],
              pathPoints3D: [
                [2.5, 0.2, 0.5],
                [2.8, 5.0, 1.2],
                [3.2, 10.0, 2.5], // projeção no teto
                [3.5, 15.0, 3.2],
                [3.6, 20.0, 2.2],
                [3.8, 25.5, 1.0],
              ],
              bolts3D: [
                { index: 1, position: [2.6, 3.0, 0.8] },
                { index: 2, position: [2.8, 5.5, 1.3] },
                { index: 3, position: [3.0, 8.0, 2.0] },
                { index: 4, position: [3.2, 10.5, 2.6] },
                { index: 5, position: [3.4, 13.0, 3.0] },
                { index: 6, position: [-3.5, 15.5, 3.2] },
                { index: 7, position: [3.5, 18.0, 2.8] },
                { index: 8, position: [3.6, 20.5, 2.1] },
                { index: 9, position: [3.7, 23.0, 1.5] },
                { index: 10, position: [3.8, 25.5, 1.0] },
              ],
              anchor3D: [3.8, 25.5, 1.0],
            },
            geometry2D: {
              routeId: 'route-super-heroi',
              color: '#F59E0B',
              startPoint: { x: 0.68, y: 0.95 },
              pathPoints: [
                { x: 0.68, y: 0.95 },
                { x: 0.70, y: 0.72 },
                { x: 0.73, y: 0.50 },
                { x: 0.75, y: 0.30 },
                { x: 0.76, y: 0.12 },
              ],
              bolts: [
                { index: 1, x: 0.69, y: 0.85 },
                { index: 2, x: 0.70, y: 0.75 },
                { index: 3, x: 0.71, y: 0.65 },
                { index: 4, x: 0.72, y: 0.55 },
                { index: 5, x: 0.73, y: 0.45 },
                { index: 6, x: 0.74, y: 0.35 },
                { index: 7, x: 0.75, y: 0.25 },
                { index: 8, x: 0.76, y: 0.15 },
              ],
              anchor: { x: 0.76, y: 0.12 },
            },
          },
          {
            id: 'route-andorinhas',
            wallId: 'wall-olhos-principal',
            orderIndex: 4,
            name: 'Canto das Andorinhas',
            grade: {
              brazilian: '5º sup',
              french: '5c',
              yds: '5.9',
              danger: 'E1',
            },
            heightMeters: 16,
            pitchesCount: 1,
            boltsCount: 7,
            anchorType: 'dupla_com_anel',
            style: 'esportiva',
            firstAscent: {
              climbers: ['Marcos Castro'],
              year: 1996,
            },
            description: 'Via agradável pela canaleta da direita. Ótima para iniciantes com excelente linha de pés e buracos generosos.',
            geometry3D: {
              routeId: 'route-andorinhas',
              color: '#3B82F6',
              tubeRadius: 0.05,
              startPoint3D: [7.0, 0.2, 0.2],
              pathPoints3D: [
                [7.0, 0.2, 0.2],
                [6.8, 4.0, 0.5],
                [6.7, 8.0, 0.7],
                [6.5, 12.0, 0.8],
                [6.3, 16.0, 0.6],
              ],
              bolts3D: [
                { index: 1, position: [6.9, 3.0, 0.4] },
                { index: 2, position: [6.8, 6.0, 0.6] },
                { index: 3, position: [6.7, 9.0, 0.7] },
                { index: 4, position: [6.6, 12.0, 0.8] },
                { index: 5, position: [6.4, 14.5, 0.7] },
                { index: 6, position: [6.3, 16.0, 0.6] },
              ],
              anchor3D: [6.3, 16.0, 0.6],
            },
            geometry2D: {
              routeId: 'route-andorinhas',
              color: '#3B82F6',
              startPoint: { x: 0.86, y: 0.92 },
              pathPoints: [
                { x: 0.86, y: 0.92 },
                { x: 0.87, y: 0.72 },
                { x: 0.88, y: 0.52 },
                { x: 0.89, y: 0.35 },
              ],
              bolts: [
                { index: 1, x: 0.86, y: 0.80 },
                { index: 2, x: 0.87, y: 0.65 },
                { index: 3, x: 0.88, y: 0.50 },
                { index: 4, x: 0.89, y: 0.35 },
              ],
              anchor: { x: 0.89, y: 0.35 },
            },
          }
        ]
      }
    ]
  },
  {
    id: 'sector-rio-barrinha',
    name: 'Setor Barrinha',
    cragName: 'Floresta da Tijuca',
    region: 'Zona Sul / Barra',
    city: 'Rio de Janeiro',
    state: 'RJ',
    coordinates: {
      latitude: -23.0084,
      longitude: -43.2982,
    },
    elevationMeters: 420,
    approachTimeMinutes: 15,
    approachTrailDescription: 'Caminhada rápida em trilha sombreada na mata atlântica. Subida íngreme com corrimão de corda no trecho final.',
    accessStatus: 'aberto',
    history: 'Ponto tradicional da escalada carioca com vista privilegiada para o mar de São Conrado e Barra.',
    rules: ['Parque Nacional da Tijuca: não colher plantas nativas nem alimentar micos.'],
    walls: [
      {
        id: 'wall-barrinha-leste',
        sectorId: 'sector-rio-barrinha',
        name: 'Parede Leste (Barrinha)',
        orientation: 'L',
        sunShadeNotes: 'Sol pela manhã bem cedo. Da metade da manhã em diante fica toda na sombra.',
        heightMeters: 24,
        rockType: 'granito',
        approachNotes: 'Basta seguir a trilha até o platô de pedras planas.',
        fallbackPhotoUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
        photos: [
          {
            id: 'photo-barrinha-1',
            url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
            caption: 'Face de granito sólido da Barrinha',
            isMain: true,
          }
        ],
        // NÍVEL 2: SEM MODELO 3D AINDA, MAS COM CROQUI 2D INTERATIVO ATIVO!
        activeTopo2D: {
          id: 'topo-barrinha-2d',
          wallId: 'wall-barrinha-leste',
          imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
          width: 1200,
          height: 800,
          aspectRatio: 1.5,
          photographer: 'Guia de Escalada do Rio',
        },
        routes: [
          {
            id: 'route-barrinha-esporao',
            wallId: 'wall-barrinha-leste',
            orderIndex: 1,
            name: 'Esporão do Corvo',
            grade: {
              brazilian: '6º',
              french: '6a',
              yds: '5.10a',
              danger: 'E1',
            },
            heightMeters: 18,
            pitchesCount: 1,
            boltsCount: 7,
            anchorType: 'dupla_com_anel',
            style: 'esportiva',
            description: 'Escalada clássica em aresta de granito com lances aéreos e boa aderência de sapatilha.',
            geometry2D: {
              routeId: 'route-barrinha-esporao',
              color: '#3B82F6',
              startPoint: { x: 0.22, y: 0.90 },
              pathPoints: [
                { x: 0.22, y: 0.90 },
                { x: 0.24, y: 0.70 },
                { x: 0.25, y: 0.50 },
                { x: 0.26, y: 0.30 },
              ],
              bolts: [
                { index: 1, x: 0.23, y: 0.80 },
                { index: 2, x: 0.24, y: 0.65 },
                { index: 3, x: 0.25, y: 0.45 },
                { index: 4, x: 0.26, y: 0.30 },
              ],
              anchor: { x: 0.26, y: 0.30 },
            },
          },
          {
            id: 'route-barrinha-directa',
            wallId: 'wall-barrinha-leste',
            orderIndex: 2,
            name: 'Directa da Barrinha',
            grade: {
              brazilian: '7c',
              french: '6c',
              yds: '5.11a',
              danger: 'E2',
            },
            heightMeters: 24,
            pitchesCount: 1,
            boltsCount: 9,
            anchorType: 'corrente',
            style: 'esportiva',
            description: 'Linha vertical imponente com cristais pontiagudos de quartzo e passagem fina no terço médio.',
            geometry2D: {
              routeId: 'route-barrinha-directa',
              color: '#EC4899',
              startPoint: { x: 0.55, y: 0.92 },
              pathPoints: [
                { x: 0.55, y: 0.92 },
                { x: 0.56, y: 0.68 },
                { x: 0.57, y: 0.42 },
                { x: 0.58, y: 0.18 },
              ],
              bolts: [
                { index: 1, x: 0.55, y: 0.82 },
                { index: 2, x: 0.56, y: 0.68 },
                { index: 3, x: 0.57, y: 0.52 },
                { index: 4, x: 0.57, y: 0.35 },
                { index: 5, x: 0.58, y: 0.18 },
              ],
              anchor: { x: 0.58, y: 0.18 },
            },
          }
        ]
      }
    ]
  },
  {
    id: 'sector-sabara-rachada',
    name: 'Pedra Rachada',
    cragName: 'Serra da Piedade',
    region: 'Grande BH',
    city: 'Sabará',
    state: 'MG',
    coordinates: {
      latitude: -19.8920,
      longitude: -43.8115,
    },
    elevationMeters: 980,
    approachTimeMinutes: 10,
    approachTrailDescription: 'Acesso muito fácil, a apenas 10 minutos do estacionamento da estrada de terra.',
    accessStatus: 'aberto',
    history: 'Falésia histórica de quartzito descoberta pelos pioneiros da escalada mineira nos anos 80.',
    walls: [
      {
        id: 'wall-rachada-setor-sol',
        sectorId: 'sector-sabara-rachada',
        name: 'Parede do Sol Nascente',
        orientation: 'L',
        sunShadeNotes: 'Sol até as 13h. Muito quente pela manhã.',
        heightMeters: 18,
        rockType: 'quartzito',
        approachNotes: 'Primeiro bloco à esquerda.',
        fallbackPhotoUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
        photos: [
          {
            id: 'photo-rachada-1',
            url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
            caption: 'Foto da Parede do Sol Nascente',
            isMain: true,
          }
        ],
        // NÍVEL 3: NEM 3D, NEM CROQUI INTERATIVO -> FOTO SIMPLES COM LISTA ORDENADA ESQ -> DIR
        routes: [
          {
            id: 'route-rachada-1',
            wallId: 'wall-rachada-setor-sol',
            orderIndex: 1,
            name: 'Trilhos da Aurora',
            grade: {
              brazilian: '5º',
              french: '5b',
              yds: '5.8',
              danger: 'E1',
            },
            heightMeters: 15,
            pitchesCount: 1,
            boltsCount: 5,
            anchorType: 'dupla_com_anel',
            style: 'esportiva',
            description: 'Via bem protegida pela fenda da esquerda em quartzito de excelente atrito.',
          },
          {
            id: 'route-rachada-2',
            wallId: 'wall-rachada-setor-sol',
            orderIndex: 2,
            name: 'Fenda dos Mineiros',
            grade: {
              brazilian: '6º sup',
              french: '6a+',
              yds: '5.10b',
              danger: 'E2',
            },
            heightMeters: 18,
            pitchesCount: 1,
            boltsCount: 6,
            anchorType: 'corrente',
            style: 'mista',
            description: 'Inicia em proteção fixa e exige peças móveis (Camalots #1 e #2) na fenda diagonal.',
          }
        ]
      }
    ]
  }
];

export const INITIAL_LOGBOOK_ENTRIES = [
  {
    id: 'log-1',
    routeId: 'route-vitamina-a',
    routeName: 'Vitamina A',
    wallName: 'Paredão Principal (Olhos)',
    sectorName: 'Falésia dos Olhos (Serra do Cipó)',
    gradeStr: '6º sup',
    date: '2026-08-15',
    style: 'onsight' as const,
    ratingStars: 5 as const,
    personalNotes: 'Sensacional! Aquecimento perfeito com muito atrito e temperatura agradável.',
    partner: 'Mariana Lima',
  },
  {
    id: 'log-2',
    routeId: 'route-gis',
    routeName: 'Gis',
    wallName: 'Paredão Principal (Olhos)',
    sectorName: 'Falésia dos Olhos (Serra do Cipó)',
    gradeStr: '7a',
    date: '2026-08-15',
    style: 'redpoint' as const,
    ratingStars: 4 as const,
    personalNotes: 'Encadenei na 2ª tentativa após descansar no platô. Passagem técnica de pés.',
    partner: 'Mariana Lima',
  }
];
